/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Container;
import javax.swing.JFrame;

/**
 *
 * @author Luis Miguel Calvo Magaz, Alvaro Gonzalez Iglesias.
 */
public class NumberAddition_v2 extends javax.swing.JFrame {

    /**
     * Creates new form NumberAddition_v2
     */
    public NumberAddition_v2() {
        initComponents();
    }

    private float ans;

    public float getAns() {
        return ans;
    }

    public void setAns(float ans) {
        this.ans = ans;
    }
    
    private int operacion;

    public int getOperacion() {
        return operacion;
    }

    public void setOperacion(int operacion) {
        this.operacion = operacion;
    }
    
    private int jTextFieldSelection;
    
    public void setTextFieldSelected(int value){
        jTextFieldSelection = value;
    }
    public int getTextFieldSelected(){
        return jTextFieldSelection;
    }
    
    public boolean isInteger( String input )
    {
        try
        {
          Float.parseFloat(input);
          return true;
        }
        catch( Exception e )
        {
            return false;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButtonChange = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabelError = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonn7 = new javax.swing.JButton();
        jButtonn8 = new javax.swing.JButton();
        jButtonn9 = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonn4 = new javax.swing.JButton();
        jButtonn5 = new javax.swing.JButton();
        jButtonn6 = new javax.swing.JButton();
        jButtonSubstraction = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButtonn1 = new javax.swing.JButton();
        jButtonn2 = new javax.swing.JButton();
        jButtonn3 = new javax.swing.JButton();
        jButtonMultiply = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButtonAns = new javax.swing.JButton();
        jButtonn0 = new javax.swing.JButton();
        jButtonPeriod = new javax.swing.JButton();
        jButtonDivide = new javax.swing.JButton();
        jButtonSolve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true), "Number Addition v2"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("First Number:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jLabel1, gridBagConstraints);

        jTextField1.setFocusCycleRoot(true);
        jTextField1.setFocusTraversalPolicyProvider(true);
        jTextField1.setNextFocusableComponent(jTextField2);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 8.0;
        jPanel3.add(jTextField1, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Second Number:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jLabel2, gridBagConstraints);

        jTextField2.setFocusCycleRoot(true);
        jTextField2.setFocusTraversalPolicyProvider(true);
        jTextField2.setNextFocusableComponent(jTextField1);
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(jTextField2, gridBagConstraints);

        jLabel3.setText("Result:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jLabel3, gridBagConstraints);

        jTextField3.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(jTextField3, gridBagConstraints);

        jButtonChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1488384724_arrowupdown.png"))); // NOI18N
        jButtonChange.setToolTipText("");
        jButtonChange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonChange.setFocusable(false);
        jButtonChange.setMaximumSize(new java.awt.Dimension(55, 43));
        jButtonChange.setMinimumSize(new java.awt.Dimension(0, 0));
        jButtonChange.setPreferredSize(new java.awt.Dimension(16, 16));
        jButtonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.weightx = 0.7;
        jPanel3.add(jButtonChange, gridBagConstraints);

        jPanel5.setMinimumSize(new java.awt.Dimension(16, 16));
        jPanel5.setPreferredSize(new java.awt.Dimension(16, 16));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(jPanel5, gridBagConstraints);

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(null);
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField4.setFocusable(false);
        jTextField4.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField4.setPreferredSize(new java.awt.Dimension(20, 20));
        jTextField4.setRequestFocusEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jTextField4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 1, 3);
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel4.setAutoscrolls(true);
        jPanel4.setPreferredSize(new java.awt.Dimension(434, 31));

        jLabelError.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelError.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(133, 133, 133))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        jPanel1.add(jPanel4, gridBagConstraints);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(4, 6));

        jButtonn7.setBackground(new java.awt.Color(0, 0, 0));
        jButtonn7.setForeground(new java.awt.Color(255, 255, 255));
        jButtonn7.setText("7");
        jButtonn7.setToolTipText("");
        jButtonn7.setAlignmentY(0.0F);
        jButtonn7.setBorder(null);
        jButtonn7.setBorderPainted(false);
        jButtonn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonn7.setFocusable(false);
        jButtonn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonn7);

        jButtonn8.setBackground(new java.awt.Color(0, 0, 0));
        jButtonn8.setForeground(new java.awt.Color(255, 255, 255));
        jButtonn8.setText("8");
        jButtonn8.setBorder(null);
        jButtonn8.setBorderPainted(false);
        jButtonn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonn8.setFocusable(false);
        jButtonn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonn8);

        jButtonn9.setBackground(new java.awt.Color(0, 0, 0));
        jButtonn9.setForeground(new java.awt.Color(255, 255, 255));
        jButtonn9.setText("9");
        jButtonn9.setBorder(null);
        jButtonn9.setBorderPainted(false);
        jButtonn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonn9.setFocusable(false);
        jButtonn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonn9);

        jButtonAdd.setBackground(new java.awt.Color(255, 102, 0));
        jButtonAdd.setText("+");
        jButtonAdd.setBorderPainted(false);
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.setFocusable(false);
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAdd);

        jButtonClear.setText("AC");
        jButtonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonClear);

        jButtonn4.setBackground(new java.awt.Color(0, 0, 0));
        jButtonn4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonn4.setText("4");
        jButtonn4.setBorderPainted(false);
        jButtonn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonn4.setFocusable(false);
        jButtonn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonn4);

        jButtonn5.setBackground(new java.awt.Color(0, 0, 0));
        jButtonn5.setForeground(new java.awt.Color(255, 255, 255));
        jButtonn5.setText("5");
        jButtonn5.setBorderPainted(false);
        jButtonn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonn5.setFocusable(false);
        jButtonn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonn5);

        jButtonn6.setBackground(new java.awt.Color(0, 0, 0));
        jButtonn6.setForeground(new java.awt.Color(255, 255, 255));
        jButtonn6.setText("6");
        jButtonn6.setBorderPainted(false);
        jButtonn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonn6.setFocusable(false);
        jButtonn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonn6);

        jButtonSubstraction.setBackground(new java.awt.Color(255, 102, 0));
        jButtonSubstraction.setText("-");
        jButtonSubstraction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSubstraction.setFocusable(false);
        jButtonSubstraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubstractionActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSubstraction);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        jButtonn1.setBackground(new java.awt.Color(0, 0, 0));
        jButtonn1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonn1.setText("1");
        jButtonn1.setBorderPainted(false);
        jButtonn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonn1.setFocusable(false);
        jButtonn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonn1);

        jButtonn2.setBackground(new java.awt.Color(0, 0, 0));
        jButtonn2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonn2.setText("2");
        jButtonn2.setBorderPainted(false);
        jButtonn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonn2.setFocusable(false);
        jButtonn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonn2);

        jButtonn3.setBackground(new java.awt.Color(0, 0, 0));
        jButtonn3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonn3.setText("3");
        jButtonn3.setBorderPainted(false);
        jButtonn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonn3.setFocusable(false);
        jButtonn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonn3);

        jButtonMultiply.setBackground(new java.awt.Color(255, 102, 0));
        jButtonMultiply.setText("X");
        jButtonMultiply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMultiply.setFocusable(false);
        jButtonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplyActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonMultiply);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7);

        jButtonAns.setBackground(new java.awt.Color(153, 153, 153));
        jButtonAns.setText("Ans");
        jButtonAns.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAns.setFocusable(false);
        jButtonAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnsActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAns);

        jButtonn0.setBackground(new java.awt.Color(0, 0, 0));
        jButtonn0.setForeground(new java.awt.Color(255, 255, 255));
        jButtonn0.setText("0");
        jButtonn0.setBorderPainted(false);
        jButtonn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonn0.setFocusable(false);
        jButtonn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonn0);

        jButtonPeriod.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPeriod.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPeriod.setText(".");
        jButtonPeriod.setBorderPainted(false);
        jButtonPeriod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeriodActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPeriod);

        jButtonDivide.setBackground(new java.awt.Color(255, 102, 0));
        jButtonDivide.setText("/");
        jButtonDivide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDivide.setFocusable(false);
        jButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivideActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDivide);

        jButtonSolve.setBackground(new java.awt.Color(153, 153, 153));
        jButtonSolve.setText("=");
        jButtonSolve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSolve.setFocusable(false);
        jButtonSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolveActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSolve);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn7ActionPerformed
        appendText(7);
    }//GEN-LAST:event_jButtonn7ActionPerformed

    private void jButtonPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeriodActionPerformed
        switch(getTextFieldSelected()){
            case 1:
                jTextField1.setText(jTextField1.getText().substring(0, jTextField1.getSelectionStart())+"."+jTextField1.getText().substring(jTextField1.getSelectionStart()));
                break;
            case 2:
                jTextField2.setText(jTextField2.getText().substring(0, jTextField2.getSelectionStart())+"."+jTextField2.getText().substring(jTextField2.getSelectionStart()));
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jButtonPeriodActionPerformed

    private void jButtonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplyActionPerformed
        jTextField4.setText("x");

        setOperacion(4);
    }//GEN-LAST:event_jButtonMultiplyActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jLabelError.setText("");
        jTextField4.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnsActionPerformed
       switch(getTextFieldSelected()){
            case 1:
                jTextField1.setText(String.valueOf(getAns()));
                break;
            case 2:
                jTextField2.setText(String.valueOf(getAns()));
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jButtonAnsActionPerformed

    private void jButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivideActionPerformed
        jTextField4.setText("/");

        setOperacion(3);
    }//GEN-LAST:event_jButtonDivideActionPerformed

    private void jButtonSubstractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubstractionActionPerformed
        jTextField4.setText("-");
        
        setOperacion(2);
    }//GEN-LAST:event_jButtonSubstractionActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        
        jTextField4.setText("+");
        
        setOperacion(1);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn3ActionPerformed
        appendText(3);
    }//GEN-LAST:event_jButtonn3ActionPerformed

    private void jButtonn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn0ActionPerformed
        appendText(0);
    }//GEN-LAST:event_jButtonn0ActionPerformed

    private void jButtonn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn6ActionPerformed
        appendText(6);
    }//GEN-LAST:event_jButtonn6ActionPerformed

    private void jButtonn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn9ActionPerformed
        appendText(9);
    }//GEN-LAST:event_jButtonn9ActionPerformed

    private void jButtonn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn8ActionPerformed
        appendText(8);
    }//GEN-LAST:event_jButtonn8ActionPerformed

    private void jButtonn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn5ActionPerformed
        appendText(5);
    }//GEN-LAST:event_jButtonn5ActionPerformed

    private void jButtonn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn4ActionPerformed
        appendText(4);
    }//GEN-LAST:event_jButtonn4ActionPerformed

    private void jButtonn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn1ActionPerformed
        appendText(1);
    }//GEN-LAST:event_jButtonn1ActionPerformed

    private void jButtonn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn2ActionPerformed
        appendText(2);
    }//GEN-LAST:event_jButtonn2ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        setTextFieldSelected(1);
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        setTextFieldSelected(2);
    }//GEN-LAST:event_jTextField2FocusGained

    private void jButtonSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolveActionPerformed
        int ope = getOperacion();
        float num1, num2, result;
        if (!isInteger(jTextField1.getText())){
            jLabelError.setText("El primer numero no es una cifra");
        }
        else if(!isInteger(jTextField2.getText())){
            jLabelError.setText("El segundo numero no es una cifra");
        }
        else{
            num1 = Float.parseFloat(jTextField1.getText());
            num2 = Float.parseFloat(jTextField2.getText());
            switch(ope){
                case 1:
                    result = num1+num2;
                    break;
                case 2:
                    result = num1-num2;
                    break;
                case 3:
                    result = num1/num2;
                    break;
                case 4:
                    result = num1*num2;
                    break;
                default:
                    result = 0;
            }
            System.out.println(result);
            jTextField3.setText(String.valueOf(result));
            setAns(result);
        }
    }//GEN-LAST:event_jButtonSolveActionPerformed

    private void jButtonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeActionPerformed

        String temp = jTextField1.getText();
        jTextField1.setText(jTextField2.getText());
        jTextField2.setText(temp);
        if(getTextFieldSelected()==1){
            jTextField2.requestFocus();
            setTextFieldSelected(2);
        }
        else{
            jTextField1.requestFocus();
            setTextFieldSelected(1);
        }
    }//GEN-LAST:event_jButtonChangeActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        
    }//GEN-LAST:event_jTextField4ActionPerformed
                                      
    private void appendText(int numero){
        String temp;
        switch(getTextFieldSelected()){
            case 1:
                jTextField1.setText(jTextField1.getText().substring(0, jTextField1.getSelectionStart())+numero+jTextField1.getText().substring(jTextField1.getSelectionStart()));
                break;
            case 2:
                jTextField2.setText(jTextField2.getText().substring(0, jTextField2.getSelectionStart())+numero+jTextField2.getText().substring(jTextField2.getSelectionStart()));
                break;
            default:
                break;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumberAddition_v2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumberAddition_v2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumberAddition_v2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberAddition_v2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumberAddition_v2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAns;
    private javax.swing.JButton jButtonChange;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDivide;
    private javax.swing.JButton jButtonMultiply;
    private javax.swing.JButton jButtonPeriod;
    private javax.swing.JButton jButtonSolve;
    private javax.swing.JButton jButtonSubstraction;
    private javax.swing.JButton jButtonn0;
    private javax.swing.JButton jButtonn1;
    private javax.swing.JButton jButtonn2;
    private javax.swing.JButton jButtonn3;
    private javax.swing.JButton jButtonn4;
    private javax.swing.JButton jButtonn5;
    private javax.swing.JButton jButtonn6;
    private javax.swing.JButton jButtonn7;
    private javax.swing.JButton jButtonn8;
    private javax.swing.JButton jButtonn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
